steps:
  - name: 'gcr.io/fabled-buckeye-364706/gcloud-terraform:latest' #create this docker image using the dockerfile
    id: Create the terraform resources
    entrypoint: 'bash'
    args:
      - '-eEuo'
      - 'pipefail'
      - '-c'
      - |
        make all-resource

logsBucket: 'gs://hellofire'
options:
  logging: GCS_ONLY
timeout: 86400s
